server:
  port: 8096
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mallikarjun986/config-server/
          clone-on-start: true